
class TaskAlreadyExistsError(Exception):
    pass


class TaskNotFoundError(Exception):
    pass
